// <auto-generated />
using ASPNET_Boilerplate.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPNET_Boilerplate.Migrations {
  [DbContext(typeof(DataContext))]
  partial class DataContextModelSnapshot : ModelSnapshot {
    protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

      modelBuilder.Entity("ASPNET_Boilerplate.Models.User", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("INTEGER");

        b.Property<string>("Email")
            .HasColumnType("TEXT");

        b.Property<string>("Name")
            .HasColumnType("TEXT");

        b.Property<string>("Password")
            .HasColumnType("TEXT");

        b.Property<string>("Username")
            .HasColumnType("TEXT");

        b.HasKey("Id");

        b.ToTable("Users");
      });
#pragma warning restore 612, 618
    }
  }
}
